# Generated by Django 5.2.6 on 2025-11-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('TH', 'Theory'), ('PR', 'Practical'), ('TU', 'Tutorial')], default='TH', max_length=2),
        ),
    ]
