# Generated by Django 5.2.6 on 2025-11-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_subject_subject_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('term', 'Term'), ('induction', 'Induction'), ('instruction', 'Instruction'), ('exam_mid', 'Mid Term Exam'), ('exam_backlog', 'Term End Exam (Backlog)'), ('exam_regular', 'Term End Exam (Regular)'), ('vacation', 'Vacation'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
