# Generated by Django 5.2.6 on 2025-11-05 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('term', 'Term'), ('induction', 'Induction'), ('instruction', 'Instruction'), ('exam_mid', 'Mid Term Exam'), ('exam_backlog', 'Term End Exam (Backlog)'), ('exam_regular', 'Term End Exam (Regular)'), ('vacation', 'Vacation'), ('holiday', 'Holiday'), ('other', 'Other')], default='other', max_length=20)),
                ('academic_year', models.CharField(max_length=9)),
                ('instructional_days', models.IntegerField(blank=True, null=True)),
                ('working_days', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('academic_year', models.CharField(max_length=9)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_timetable', to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.timeslot')),
            ],
            options={
                'ordering': ['time_slot__day', 'time_slot__start_time'],
                'unique_together': {('teacher', 'time_slot', 'academic_year')},
            },
        ),
        migrations.DeleteModel(
            name='AcademicEvent',
        ),
    ]
