# Generated by Django 5.2.6 on 2025-10-22 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('academic', 'Academic'), ('exam', 'Exam'), ('fee', 'Fee'), ('event', 'Event'), ('announcement', 'Announcement'), ('alert', 'Alert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All'), ('all_students', 'All Students'), ('all_teachers', 'All Teachers'), ('class', 'Specific Class'), ('department', 'Specific Department'), ('individual_student', 'Individual Student'), ('individual_teacher', 'Individual Teacher')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='students.student'),
        ),
    ]
